"""Honest (hard-negative) seeds for the fast routine.

Each category: 10 hand-written seeds as (language, text) plus 3 slot
templates; every seed and template is one template_family, kept inside a
single round. They deliberately share scam vocabulary (codes, fees, links,
urgency, "don't share") so wording alone isn't enough. Links and phone
placeholders are drawn from the SAME pool as scams, so link style can't
give the label away.
"""

LEGIT = {
    "bank transaction alert": {
        "seeds": [
            ("English", "{bank}: {amount} debited from your account ending 4821 at a grocery store. Not you? Call the number on the back of your card."),
            ("English", "{bank}: salary of {amount} credited to your account. Available balance updated in the app."),
            ("English", "Your card ending 1190 was used for {amount} online. If this wasn't you, block the card in the app."),
            ("English", "{bank}: your monthly statement is ready. View it in online banking. We never ask for your PIN."),
            ("English", "Standing order of {amount} to your landlord was paid today."),
            ("English", "{bank}: ATM withdrawal of {amount} on {day}. Questions? Visit any branch."),
            ("English", "A new payee was added to your account. If you did not do this, contact us on {phone}."),
            ("English", "{bank}: your fixed deposit of {amount} matures on {day}. No action needed, it renews automatically."),
            ("Hinglish", "{bank}: aapke account se {amount} debit hue. Aapne nahi kiya to card ke peeche diye number pe call karein."),
            ("Manglish", "{bank}: ningalude account il ninnu {amount} debit aayi. Ningal alla enkil card inte purakile number il vilikkuka."),
        ],
        "templates": [
            "{bank}: {amount} {direction} {where} on {day}. {note}",
            "{bank} alert: card ending {last4} used for {amount}. {note}",
            "Your {bank} balance after today's {txn} is updated. {note}",
        ],
        "slots": {
            "direction": ["debited from your account", "credited to your account", "paid by card"],
            "where": ["at a supermarket", "at a fuel station", "online", "at a pharmacy", "via net banking"],
            "last4": ["4821", "1190", "7734", "0562"],
            "txn": ["transfer", "card payment", "withdrawal", "deposit"],
            "note": ["Not you? Call the number on your card.", "No action needed.", "View details in the app.",
                     "We will never ask for your PIN or OTP."],
        },
    },
    "OTP with do-not-share": {
        "seeds": [
            ("English", "{code} is your login code for {brand}. Do not share it with anyone, including our staff."),
            ("English", "Your verification code is {code}. It expires in 10 minutes. Never share this code."),
            ("English", "Use {code} to confirm your payment of {amount}. Our team will never call you to ask for it."),
            ("English", "{brand}: {code} is your one-time password. If you didn't request it, ignore this message."),
            ("English", "Your password reset code is {code}. If this wasn't you, change your password now."),
            ("English", "Sign-in attempt on a new device. Code {code}. Do not give this code to anyone who calls you."),
            ("English", "{code} is your delivery confirmation code. Only share it with the courier at your door."),
            ("English", "Your two-step code: {code}. {brand} will never ask for this by phone or email."),
            ("Hinglish", "{code} aapka OTP hai. Ise kisi ke saath share na karein, bank kabhi OTP nahi maangta."),
            ("Manglish", "{code} aanu ningalude OTP. Ithu aarumaayi share cheyyaruthu, bank orikkalum OTP chodikkilla."),
        ],
        "templates": [
            "{code} is your {purpose} code for {brand}. {warning}",
            "{brand}: use {code} to {action}. {warning}",
            "Your {purpose} code is {code}, valid for {minutes} minutes. {warning}",
        ],
        "slots": {
            "purpose": ["login", "verification", "payment", "reset", "sign-in"],
            "action": ["sign in", "confirm your payment", "verify your number", "reset your password"],
            "minutes": ["5", "10", "15"],
            "warning": ["Do not share it with anyone.", "Never share this code, not even with our staff.",
                        "We will never call to ask for it.", "If you didn't request it, ignore this."],
        },
    },
    "delivery update": {
        "seeds": [
            ("English", "Your {courier} parcel is out for delivery today between 10am and 2pm. Track it at {link}"),
            ("English", "We missed you today. Your parcel is at the local pickup point, bring ID to collect it."),
            ("English", "Your order has shipped and should arrive by {day}. No action needed."),
            ("English", "{courier}: your package was delivered and left with your neighbour."),
            ("English", "Delivery rescheduled to {day} due to weather. Sorry for the delay."),
            ("English", "Your parcel is held at the depot because nobody was home. You can rebook a free delivery in the app."),
            ("English", "Your food order is on the way, the rider will arrive in about 15 minutes."),
            ("English", "Your return has been picked up. Your refund will be processed once it reaches our warehouse."),
            ("Hinglish", "Aapka order dispatch ho gaya hai, {day} tak deliver ho jayega. App mein track karein."),
            ("Manglish", "Ningalude order dispatch aayi, {day} kku munpu deliver aakum. App il track cheyyuka."),
        ],
        "templates": [
            "{courier}: your parcel {status}. {extra}",
            "Order update: your parcel {status}. Expected {day}. {extra}",
            "Your {item} is {status}. {extra}",
        ],
        "slots": {
            "status": ["is out for delivery", "has shipped", "was delivered", "is at the pickup point", "is delayed by a day"],
            "item": ["order", "parcel", "package", "return"],
            "extra": ["No action needed.", "Track it in the app.", "Bring ID to collect.", "Reply STOP for no updates."],
        },
    },
    "real urgent family message": {
        "seeds": [
            ("English", "Mum, I'm at A&E with {name}, she twisted her ankle, nothing serious. Can you pick us up at 6?"),
            ("English", "Dad urgent: the boiler is leaking, can you call the plumber? I've turned the water off."),
            ("English", "Grandpa's in hospital for a check-up, he's fine. Visiting hours are 4 to 6 if you want to come."),
            ("English", "Call me when you see this, it's about the school pickup today, not an emergency."),
            ("English", "I left my keys at home, are you back before 7? If not I'll wait at {name}'s."),
            ("English", "Car broke down on the ring road, waiting for the recovery truck. I'm fine, will be late."),
            ("English", "Hey, it's me on {name}'s phone, mine died. I'm at the cinema, home by 10."),
            ("English", "The dog got out again, he's back now. Can you fix the gate latch this weekend?"),
            ("Hinglish", "Mummy main hospital mein hoon, dadi ka checkup hai, sab theek hai. 6 baje aa jaana."),
            ("Manglish", "Amma, njan hospital il aanu, ammoommaykku checkup aanu, kuzhappamilla. 6 manikku varu."),
        ],
        "templates": [
            "{relative}, {situation}. {reassure} {ask}",
            "Urgent but not serious: {situation}. {ask}",
            "It's me, {situation}. {reassure}",
        ],
        "slots": {
            "relative": ["Mum", "Dad", "Grandma", "Sis"],
            "situation": ["I'm at the clinic with a sprained wrist", "the car won't start", "I missed the last bus",
                          "the kitchen tap burst", "my phone is on 2%"],
            "reassure": ["I'm fine.", "Nothing serious.", "No need to worry.", "All okay now."],
            "ask": ["Can you pick me up at 6?", "Call me when free.", "Can you ring the plumber?", "Wait up for me."],
        },
    },
    "work message with deadline": {
        "seeds": [
            ("English", "Reminder: the quarterly report is due by 5pm today. Please upload it to the shared drive."),
            ("English", "Can you send me the updated slides before the 3pm client call? Thanks."),
            ("English", "Urgent: payroll closes tomorrow, please submit your timesheet tonight."),
            ("English", "The invoice from {company} needs approval by Friday, it's in your queue."),
            ("English", "Heads up, the audit team is visiting on {day}. Please make sure receipts are uploaded."),
            ("English", "Server maintenance tonight at 11pm, save your work and log off before then."),
            ("English", "Please review the contract draft and add comments by end of day."),
            ("English", "Team, expense claims for this month must be in by the 25th."),
            ("Hinglish", "Kal tak report submit karni hai, please aaj shaam tak bhej dena."),
            ("Manglish", "Naale report submit cheyyanam, innu vaikunneram ayachu tharamo."),
        ],
        "templates": [
            "Reminder: {task} is due {when}. {where}",
            "Can you {task_short} {when}? {why}",
            "{who} needs {task} {when}. Thanks!",
        ],
        "slots": {
            "task": ["the budget sheet", "your timesheet", "the project update", "the client proposal"],
            "task_short": ["send the slides", "approve the invoice", "check the numbers", "update the tracker"],
            "when": ["by 5pm", "before Friday", "by end of day", "before the 3pm meeting"],
            "where": ["Upload it to the shared drive.", "Email it to the team.", "Put it in the tracker."],
            "why": ["The client asked for it.", "The manager wants a look.", "We present tomorrow."],
            "who": ["Finance", "The project lead", "HR", "The client"],
        },
    },
    "real promotion": {
        "seeds": [
            ("English", "{brand} weekend sale: 30% off all shoes until Sunday. Shop in store or online."),
            ("English", "Your loyalty points balance is 1,240. Redeem them on your next visit."),
            ("English", "New arrivals are here! Members get early access this week. Reply STOP to opt out."),
            ("English", "Happy birthday from {brand}! Enjoy a free coffee this week with your member card."),
            ("English", "Flash deal: buy one get one free on pizzas tonight only. Order in the app."),
            ("English", "Your free trial ends in 3 days. You can cancel anytime in your account settings."),
            ("English", "Festival offer: extra 10% off electronics with code FEST10 at checkout."),
            ("English", "Thanks for shopping with {brand}. Rate your experience and get 5% off next time."),
            ("Hinglish", "Diwali sale shuru! Sabhi kapdon pe 30% chhoot, sirf is weekend tak. Store pe aayiye."),
            ("Manglish", "Onam offer! Ella saadhanangalkkum 25% kurav, ee aazhcha maathram. Kadayil varu."),
        ],
        "templates": [
            "{brand}: {offer} {until}. {optout}",
            "{offer} for members {until}. {optout}",
            "Hi from {brand}! {offer}. {optout}",
        ],
        "slots": {
            "offer": ["20% off everything", "free delivery on all orders", "buy one get one free", "double loyalty points"],
            "until": ["this weekend only", "until Sunday", "today only", "all week"],
            "optout": ["Reply STOP to opt out.", "T&Cs apply.", "Shop in store or online."],
        },
    },
    "government notice": {
        "seeds": [
            ("English", "Your tax return has been received and is being processed. Check status in your online account."),
            ("English", "Reminder: your vehicle insurance certificate expires next month. Renew through your insurer."),
            ("English", "Your passport application is under review. We'll write to you if we need more documents."),
            ("English", "Voter list update: verify your details at your local election office before {day}."),
            ("English", "Property tax for this year is due by the 31st. Pay at the municipal office or official portal."),
            ("English", "Your driving licence renewal appointment is confirmed for {day} at 10am."),
            ("English", "Water supply will be interrupted on {day} from 9am to 1pm for maintenance."),
            ("English", "Your pension statement for this year is now available on the official portal."),
            ("Hinglish", "Aapka tax return mil gaya hai aur process ho raha hai. Status online account mein dekhein."),
            ("Manglish", "Ningalude tax return kitti, process cheyyunnu. Status online account il nokkuka."),
        ],
        "templates": [
            "{office}: {notice}. {action}",
            "Notice: {notice} on {day}. {action}",
            "Reminder from the {office}: {notice}. {action}",
        ],
        "slots": {
            "office": ["Tax office", "Municipal office", "Transport department", "Election office"],
            "notice": ["your return is being processed", "the renewal date is approaching", "water supply will pause",
                       "your application is under review"],
            "action": ["No action needed.", "Visit the official portal for details.", "Contact your local office with questions."],
        },
    },
    "appointment reminder": {
        "seeds": [
            ("English", "Reminder: your dentist appointment is on {day} at 9:30am. Reply C to confirm or R to reschedule."),
            ("English", "Your haircut is booked for {day} at 4pm with {name}. See you then!"),
            ("English", "Clinic reminder: please arrive 10 minutes early for your blood test tomorrow. Fast from midnight."),
            ("English", "Your car service is booked for {day} morning. Drop the keys at reception."),
            ("English", "Parent-teacher meeting is on {day} at 3pm in Room 12."),
            ("English", "Your eye test is tomorrow at 11am. Bring your current glasses."),
            ("English", "Physio session moved to {day} at 2pm. Let us know if that doesn't work."),
            ("English", "Your vaccination slot is confirmed. Bring your ID card."),
            ("Hinglish", "Doctor ke saath aapka appointment {day} ko subah 10 baje hai. Confirm karne ke liye Y bhejein."),
            ("Manglish", "Doctor appointment {day} raavile 10 manikku aanu. Confirm cheyyan Y ayakkuka."),
        ],
        "templates": [
            "Reminder: your {service} is on {day} at {time}. {note}",
            "{service} confirmed for {day}, {time}. {note}",
            "See you {day} at {time} for your {service}. {note}",
        ],
        "slots": {
            "service": ["dentist visit", "haircut", "car service", "eye test", "physio session"],
            "time": ["9:30am", "11am", "2pm", "4:15pm"],
            "note": ["Reply C to confirm.", "Arrive 10 minutes early.", "Call us to reschedule.", "Bring your ID."],
        },
    },
    "UPI payment confirmation": {
        "seeds": [
            ("English", "You paid {amount} to {name} via UPI. Ref 4471023. Thank you."),
            ("English", "Received {amount} from {name} via UPI. Balance updated."),
            ("English", "Your UPI autopay of {amount} for the streaming subscription was successful."),
            ("English", "Payment of {amount} to the electricity board via UPI is successful."),
            ("English", "UPI mandate created for monthly rent of {amount}. You can cancel it anytime in the app."),
            ("English", "{name} requested {amount} for dinner split. Pay or decline in the app."),
            ("English", "Your UPI payment failed, no money was deducted. Please try again."),
            ("English", "Refund of {amount} for your cancelled order was credited to your UPI-linked account."),
            ("Hinglish", "{name} ko {amount} UPI se bhej diye gaye. Transaction safal raha."),
            ("Manglish", "{name} nu {amount} UPI vazhi ayachu. Transaction vijayichu."),
        ],
        "templates": [
            "{direction} {amount} {party} via UPI. {note}",
            "UPI: {amount} {direction_short} {name}. {note}",
            "Your UPI {txn} of {amount} {status}. {note}",
        ],
        "slots": {
            "direction": ["You paid", "You received", "Sent"],
            "party": ["to the grocery store", "from a friend", "to the canteen"],
            "direction_short": ["paid to", "received from"],
            "txn": ["autopay", "payment", "transfer"],
            "status": ["was successful", "failed, no money deducted", "is pending, check later"],
            "note": ["Ref 5520193.", "Thank you.", "Balance updated in the app."],
        },
    },
    "college circular": {
        "seeds": [
            ("English", "Semester exam fee must be paid by the 20th through the college portal only."),
            ("English", "Library books are due back before the term ends. Late returns are fined."),
            ("English", "The college will remain closed on {day} for the festival."),
            ("English", "Hall tickets for the final exams are available on the student portal."),
            ("English", "Scholarship applications are open till the 15th. Apply only through the official student portal."),
            ("English", "Practical exams begin on {day}. Check the timetable on the notice board."),
            ("English", "Hostel fees for next semester are due by month end. Pay at the accounts office."),
            ("English", "Results for the internal test are posted on the portal. Contact your class teacher for queries."),
            ("Hinglish", "Semester exam form bharne ki aakhri tareekh 20 hai, fees college portal pe hi jama karein."),
            ("Manglish", "Exam fee adakkenda avasana theeyathi 20 aanu, college portal il maathram adakkuka."),
        ],
        "templates": [
            "{office}: {notice}. {action}",
            "Circular: {notice} on {day}. {action}",
            "Students, {notice}. {action}",
        ],
        "slots": {
            "office": ["Exam cell", "Accounts office", "Principal's office", "Library"],
            "notice": ["exam fees are due", "hall tickets are ready", "the college is closed", "results are published"],
            "action": ["Use the official portal only.", "Check the notice board.", "Contact your class teacher."],
        },
    },
    "recruiter outreach": {
        "seeds": [
            ("English", "Hi {name}, I saw your profile and think you'd fit a backend role at our company. Open to a quick call this week?"),
            ("English", "Thanks for applying. We'd like to invite you to an interview on {day} at our office."),
            ("English", "Your application for the analyst role has moved to the next stage. We'll email the schedule."),
            ("English", "Hello, we're hiring for a part-time tutor role. No fees involved. Would you like details?"),
            ("English", "Congratulations, we're pleased to offer you the position. The formal offer letter is attached."),
            ("English", "Hi, are you open to new opportunities? I have a role matching your experience in marketing."),
            ("English", "Please complete the online assessment by Friday. It takes about 40 minutes."),
            ("English", "We regret to inform you that we've moved forward with another candidate. Best of luck."),
            ("Hinglish", "Namaste, humne aapka resume dekha, kya aap agle hafte interview ke liye office aa sakte hain?"),
            ("Manglish", "Namaskaram, ningalude resume kandu, adutha aazhcha interview nu office il varan pattumo?"),
        ],
        "templates": [
            "Hi {name}, {opening} at {company}. {next}",
            "{company} recruiting: {opening}. {next}",
            "Hello, {opening}. {next}",
        ],
        "slots": {
            "opening": ["we have a data role that matches your profile", "you've been shortlisted for an interview",
                        "we'd like to discuss a design opportunity"],
            "next": ["Are you free for a call this week?", "We'll email the details.", "No fees are ever charged."],
        },
    },
    "refund confirmation": {
        "seeds": [
            ("English", "Your refund of {amount} has been processed and will reach your account in 5-7 working days."),
            ("English", "We've received your returned item. Refund issued to your original payment method."),
            ("English", "Your flight cancellation refund of {amount} is complete. No further action is needed."),
            ("English", "Partial refund of {amount} for the damaged item has been credited."),
            ("English", "Your insurance claim was approved; the amount will be paid to your registered account."),
            ("English", "Overcharge corrected: {amount} refunded to your card. Sorry for the trouble."),
            ("English", "Your subscription was cancelled and the unused balance refunded."),
            ("English", "Refund status: approved. You'll see it on your next statement."),
            ("Hinglish", "Aapka refund {amount} 5 din mein original payment method mein aa jayega. Kuch karne ki zaroorat nahi."),
            ("Manglish", "Ningalude refund {amount} anchu divasathinullil account il varum. Onnum cheyyendathilla."),
        ],
        "templates": [
            "Your refund of {amount} {status}. {note}",
            "{brand}: refund for {reason} {status}. {note}",
            "Refund update: {status}. {note}",
        ],
        "slots": {
            "status": ["has been processed", "is approved", "was credited", "is on its way"],
            "reason": ["your return", "the cancelled order", "the damaged item"],
            "note": ["No action needed.", "Allow 5-7 working days.", "It goes to your original payment method."],
        },
    },
}
