"""Scam seeds, part 2 of 3. Same format as seeds_scam_a.py."""

SCAM_B = {
    "UPI collect-request or refund": {
        "in_corpus": "no",
        "seeds": [
            ("English", "I sent {amount} to your UPI by mistake, please return it. I've raised a collect request, just approve it with your PIN."),
            ("English", "Your refund of {amount} is ready. Accept the payment request in your UPI app and enter the PIN to receive it."),
            ("English", "Hello, I paid you twice for the order. Can you approve the request I sent so the extra goes back?"),
            ("English", "Cashback alert: approve the incoming request to credit {amount} to your account."),
            ("English", "Your electricity refund is pending. Tap 'Pay' on the request and enter your UPI PIN to get it."),
            ("Hinglish", "Bhai galti se aapko {amount} chale gaye. Maine request bheji hai, PIN daal ke approve kar do please."),
            ("Manglish", "Chetta, abaddhathil {amount} ningalkku ayachu. Njan request ayachittundu, PIN adichu approve cheyyamo?"),
            ("English", "Hi, it's the seller from the marketplace. My app shows the money didn't go. I've sent a request; approve and you'll get it back."),
        ],
        "templates": [
            "{who} sent you a request for {amount}. {reason} Approve it with your UPI PIN to {outcome}.",
            "Sorry, I sent {amount} to your number by mistake. I've raised a {thing}, please approve it so it {outcome2}.",
        ],
        "slots": {
            "who": ["Refund desk", "Cashback team", "A buyer", "Your bank's rewards"],
            "reason": ["Your refund is ready.", "You won a cashback.", "The order was cancelled."],
            "outcome": ["receive the money", "get your refund", "credit your cashback"],
            "thing": ["collect request", "payment request", "UPI request"],
            "outcome2": ["comes back", "reverses", "gets refunded"],
        },
    },
    "FASTag or toll balance": {
        "in_corpus": "no",
        "seeds": [
            ("English", "Your FASTag will be blacklisted today due to incomplete KYC. Update now at {link} to avoid double toll charges."),
            ("English", "FASTag balance low. Recharge now through this link to avoid penalty at the next toll plaza: {link}"),
            ("English", "Toll notice: your tag was charged twice. Claim your refund by entering your card details here."),
            ("English", "Your vehicle tag has expired. Renew it today, a fee of {amount} applies, otherwise you pay a cash penalty."),
            ("English", "Highway authority: unpaid toll found on your number plate. Settle it within 24 hours to avoid a fine."),
            ("Hinglish", "Aapka FASTag aaj block ho jayega. KYC update karein {link} pe, warna toll pe double charge lagega."),
            ("Manglish", "Ningalude FASTag innu block aakum. {link} il KYC update cheyyuka, illenkil toll il double charge."),
            ("English", "A reminder that your toll tag account needs a quick re-verification sometime this week. It only takes a minute: {link}"),
        ],
        "templates": [
            "FASTag alert: {problem}. {action} at {link} {deadline}.",
            "Your toll tag {problem}. Pay {amount} to {fix} or {consequence}.",
        ],
        "slots": {
            "problem": ["KYC is incomplete", "balance is too low", "has been suspended", "will expire today"],
            "action": ["Update details", "Recharge now", "Verify your tag", "Renew"],
            "deadline": ["today", "within 24 hours", "before your next trip"],
            "fix": ["reactivate it", "renew it", "clear the dues"],
            "consequence": ["you will pay double toll", "it will be blacklisted", "a penalty applies"],
        },
    },
    "electricity disconnection": {
        "in_corpus": "no",
        "seeds": [
            ("English", "Dear consumer, your electricity will be disconnected tonight at 9.30 pm because last month's bill was not updated. Call {phone} immediately."),
            ("English", "Power supply notice: your meter is not updated. Contact the electricity officer on {phone} to avoid disconnection."),
            ("English", "Your bill payment failed. Pay {amount} now at {link} or supply will be cut today."),
            ("English", "Your smart meter subscription has expired. Renew at {link} or the power will stop."),
            ("English", "Electricity board: please download the support app so our officer can update your meter remotely."),
            ("Hinglish", "Aapki bijli aaj raat 9 baje kaat di jayegi. Pichla bill update nahi hua. Turant {phone} pe call karein."),
            ("Manglish", "Ningalude current innu raathri 9 manikku cut cheyyum. Bill update aayilla. Udane {phone} il vilikkuka."),
            ("English", "Hello, our records show a small mismatch on your electricity account. Please give our officer a call when free so it doesn't cause trouble later."),
        ],
        "templates": [
            "{board}: your power will be {action} {when} because {reason}. Call {phone} or pay at {link}.",
            "Dear consumer, {reason}. To avoid disconnection, {fix}.",
        ],
        "slots": {
            "board": ["Electricity board", "Power supply office", "City energy department"],
            "action": ["disconnected", "cut", "suspended"],
            "when": ["tonight", "at 9.30 pm", "within 2 hours", "today"],
            "reason": ["last month's bill is not updated", "your meter is not verified", "a payment failed"],
            "fix": ["call our officer on [PHONE]", "pay the pending amount at [LINK]", "install the support app"],
        },
    },
    "KYC or Aadhaar/PAN expiry": {
        "in_corpus": "no",
        "seeds": [
            ("English", "Dear customer, your bank account will be blocked today. Your PAN card is not updated. Update KYC now: {link}"),
            ("English", "Your Aadhaar-linked KYC has expired. Click {link} and enter your details and OTP to keep your account active."),
            ("English", "Your wallet KYC is pending. Account will be suspended in 24 hours. Call {phone} to complete it."),
            ("English", "Last day to link PAN with your account. Failure will freeze your savings. Update here."),
            ("English", "Your SIM card will be deactivated as your KYC documents expired. Re-verify at {link}."),
            ("Hinglish", "Aapka KYC expire ho gaya hai, aaj account block ho jayega. {link} pe PAN aur OTP daal ke update karein."),
            ("Manglish", "Ningalude KYC expire aayi, innu account block aakum. {link} il PAN um OTP um koduthu update cheyyuka."),
            ("English", "Hi, routine reminder: our records show your KYC is due for renewal. You can do it from home in two minutes."),
        ],
        "templates": [
            "{institution}: your {doc} {problem}. Update at {link} {deadline} or your account will be {consequence}.",
            "Dear customer, {doc} verification is pending. Share the OTP sent to you with our agent on {phone} to keep the account active.",
        ],
        "slots": {
            "institution": ["Your bank", "Wallet support", "Mobile operator", "Account services"],
            "doc": ["PAN card", "Aadhaar KYC", "KYC documents", "ID details"],
            "problem": ["has expired", "is not updated", "is incomplete"],
            "deadline": ["today", "within 24 hours", "before midnight"],
            "consequence": ["blocked", "frozen", "suspended"],
        },
    },
    "courier or customs parcel held": {
        "in_corpus": "yes (parcel or delivery fee)",
        "seeds": [
            ("English", "Your parcel is held at customs. Pay the import duty of {amount} at {link} to release it."),
            ("English", "We could not deliver your package because the address is incomplete. Update it and pay a small fee: {link}"),
            ("English", "International shipment on hold. Contact our customs officer on {phone} and pay clearance charges today."),
            ("English", "Your courier contains a restricted item. To avoid legal action, call the customs desk immediately."),
            ("English", "Final notice: your package will be returned to sender in 12 hours unless the warehouse fee is paid."),
            ("Hinglish", "Aapka parcel customs mein ruka hai. {amount} duty {link} pe bharo, tab hi delivery hogi."),
            ("Manglish", "Ningalude parcel customs il pidichu vachirikkunnu. {amount} duty {link} il adachal maathram delivery."),
            ("English", "Hello, a gift parcel from overseas is waiting for you. There's just a small handling amount to sort out, reply and we'll guide you."),
        ],
        "templates": [
            "{courier}: your parcel is {status}. {ask} {amount} at {link} {deadline}.",
            "{courier} customs desk: a package in your name {problem}. Call {phone} {deadline}.",
        ],
        "slots": {
            "courier": ["SwiftShip", "ParcelHub", "GlobalPost", "Expressly"],
            "status": ["held at customs", "on hold", "awaiting payment", "at our warehouse"],
            "ask": ["Pay the duty of", "Pay the release charge of", "Pay the storage fee of"],
            "deadline": ["today", "within 12 hours", "before it is returned"],
            "problem": ["contains restricted items", "needs clearance", "was flagged at the airport"],
        },
    },
    "fake customer-care number": {
        "in_corpus": "no",
        "seeds": [
            ("English", "Thanks for contacting the airline helpline. To process your refund, download the support app and share the code that appears."),
            ("English", "I'm from the official customer care team. Your complaint is registered; pay {amount} refundable fee to activate it."),
            ("English", "We saw your post about the failed payment. Our support team can help, call {phone} and keep your banking app open."),
            ("English", "Helpdesk: to cancel your order and get money back, fill in your card number and CVV in this form: {link}"),
            ("English", "You searched for our toll-free number. Call {phone}, our executive will guide you through the refund on screen."),
            ("Hinglish", "Customer care se bol raha hoon. Refund ke liye app download karke screen par aaya code bataiye."),
            ("Manglish", "Customer care il ninnu aanu. Refund nu app download cheythu screen il varunna code parayu."),
            ("English", "Hi, this is the support desk following up on your complaint. Whenever you're free, give us a ring and we'll sort the refund together."),
        ],
        "templates": [
            "{brand} customer care: {issue}. {ask}",
            "Official {brand} helpline here about your {issue_short}. Call {phone} and {ask_short}.",
        ],
        "slots": {
            "brand": ["SkyJet Airlines", "ShopEasy", "QuickPay wallet", "Metro Rail"],
            "issue": ["your refund is approved", "your complaint is registered", "your order can be cancelled"],
            "ask": ["Share the code we just sent to finish it.", "Pay a small refundable fee to activate it.",
                    "Install our support app so we can guide you."],
            "issue_short": ["refund", "complaint", "failed payment"],
            "ask_short": ["keep your banking app open", "read out the code you receive", "install the screen-share app"],
        },
    },
    "remote-access support": {
        "in_corpus": "yes (tech support remote-access scam)",
        "seeds": [
            ("English", "Security alert: your computer is infected. Call our certified technician on {phone} and allow remote access to clean it."),
            ("English", "This is the internet provider. Your router was hacked. Please install the remote tool so we can fix it now."),
            ("English", "Your account shows unusual logins. Our engineer will connect to your phone to secure it, accept the screen-share request."),
            ("English", "Warning! Your device license expired. Call support immediately and do not restart your computer."),
            ("English", "Refund team here, we overcharged you. Open the remote desktop app and log into your bank so we can return it."),
            ("Hinglish", "Aapke computer mein virus hai. Hamara technician remote se theek karega, app install karke code bataiye."),
            ("Manglish", "Ningalude computer il virus undu. Njangalude technician remote aayi sheriyakkum, app install cheythu code parayu."),
            ("English", "Hi, it's tech support following up on the slow laptop you reported. When you're free, we can connect remotely and have a look."),
        ],
        "templates": [
            "{source}: {problem}. Call {phone} and {ask}.",
            "Our {who} needs {access} to {fix}. Please {ask} now.",
        ],
        "slots": {
            "source": ["Security alert", "Internet provider", "Device protection", "Support centre"],
            "problem": ["your computer is infected", "your router was hacked", "your license has expired"],
            "ask": ["allow remote access", "install the support tool", "accept the screen-share request"],
            "who": ["engineer", "technician", "security expert"],
            "access": ["remote access", "screen sharing", "control of your device"],
            "fix": ["remove the virus", "secure your account", "process your refund"],
        },
    },
    "boss gift-card request": {
        "in_corpus": "yes (gift-card request from a boss or colleague)",
        "seeds": [
            ("English", "Hi, are you at your desk? I need a quick favour, I'm in a board meeting. Can you buy some gift cards for a client?"),
            ("English", "It's {name}. I need 4 shopping gift cards of {amount} each for staff rewards. Scratch them and send me photos of the codes."),
            ("English", "Please keep this confidential, it's a surprise for the team. Get the cards and send me the numbers by noon."),
            ("English", "I'm travelling and can't call. Buy the e-gift cards and email me the codes, the company will reimburse you."),
            ("English", "Are you free? I need you to handle something for me discreetly today."),
            ("Hinglish", "Main meeting mein hoon, call nahi kar sakta. Client ke liye 3 gift cards le lo aur codes ki photo bhej do."),
            ("Manglish", "Njan meeting il aanu. Client nu vendi 3 gift card vangi codes inte photo ayakkamo? Aarodum parayanda."),
            ("English", "Hey, quick one when you get a chance. Could you pick up a couple of gift cards on your way in? I'll explain later."),
        ],
        "templates": [
            "Hi, it's {name}. I'm {busy}. Please buy {count} {card} gift cards and send me the codes {when}.",
            "Can you do me a favour? I need {count} {card} cards for {reason}. Keep it between us and text me the numbers.",
        ],
        "slots": {
            "busy": ["in a meeting", "on a flight", "at a conference", "with the directors"],
            "count": ["3", "4", "5", "6"],
            "card": ["shopping", "music store", "game store", "e-commerce"],
            "when": ["asap", "before noon", "in the next hour"],
            "reason": ["a client", "staff rewards", "a vendor", "a surprise"],
        },
    },
}
