import { ArrowUpRight, Clock3, ExternalLink } from "lucide-react";
import { Link } from "react-router-dom";
import { RiskBadge, StatusBadge } from "@/components/common/RiskBadge";
import type { Detection } from "@/types/trustgraph";

const formatDate = (value: string) => new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }).format(new Date(value));
export function DetectionTable({ items }: { items: Detection[] }) {
  return <div className="detection-list" data-testid="detection-results"><div className="hidden overflow-x-auto md:block"><table className="data-table"><thead><tr><th>ID</th><th>Detected</th><th>Source</th><th>Risk score</th><th>Risk level</th><th>Status</th><th><span className="sr-only">View</span></th></tr></thead><tbody>{items.map((item) => <tr key={item.id} data-testid={`detection-row-${item.id}`}><td><span className="mono-text">{item.id}</span>{item.isDemo && <span className="demo-tag">Demo data</span>}</td><td><span className="date-cell"><Clock3 size={13} />{formatDate(item.createdAt)}</span></td><td><strong>{item.site}</strong><small>{item.channel}</small></td><td><span className="mono-text score-text">{item.riskScore === null ? "Unavailable" : item.riskScore.toFixed(2)}</span></td><td><RiskBadge level={item.riskLevel} small /></td><td><StatusBadge reviewed={item.status === "reviewed"} /></td><td><Link to={`/app/detections/${item.id}`} className="view-link" data-testid={`detection-view-${item.id}`}>View <ArrowUpRight size={14} /></Link></td></tr>)}</tbody></table></div><div className="space-y-3 md:hidden">{items.map((item) => <article className="mobile-detection-card" key={item.id} data-testid={`mobile-detection-card-${item.id}`}><div className="flex items-start justify-between gap-3"><div><span className="mono-text text-xs">{item.id}</span>{item.isDemo && <span className="demo-tag">Demo data</span>}<h3>{item.site}</h3><p>{formatDate(item.createdAt)} · {item.channel}</p></div><RiskBadge level={item.riskLevel} small /></div><div className="mobile-card-footer"><span className="mono-text">score {item.riskScore === null ? "Unavailable" : item.riskScore.toFixed(2)}</span><StatusBadge reviewed={item.status === "reviewed"} /><Link to={`/app/detections/${item.id}`} className="view-link" data-testid={`mobile-detection-view-${item.id}`}>View <ExternalLink size={13} /></Link></div></article>)}</div></div>;
}
